import React from 'react';
import { render, screen, waitFor, within } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { CalendarTab } from '../src/features/calendar/components/CalendarTab.tsx';
import { CalendarEventApplicationService } from '../src/features/calendar/services/calendarEventApplicationService.ts';
import { LocalStorageCalendarEventRepository } from '../src/features/calendar/services/localStorageCalendarEventRepository.ts';
import type { CalendarEventId } from '../src/features/calendar/types/calendarEvent.ts';

let tick:number; let service:CalendarEventApplicationService;
beforeEach(()=>{localStorage.clear();tick=Date.parse('2026-08-03T00:00:00Z');service=new CalendarEventApplicationService(new LocalStorageCalendarEventRepository(),()=>new Date(tick+=1000).toISOString(),()=>`event-${tick}` as CalendarEventId)});
async function createAllDay(title='診察'){const user=userEvent.setup();render(<CalendarTab service={service}/>);await user.type(screen.getByRole('textbox',{name:'予定名'}),title);await user.click(screen.getByRole('button',{name:'予定を作成'}));return user}

describe('Calendar DOM integration',()=>{
 it('creates MANUAL ALL_DAY, edits it, and changes textual status',async()=>{const user=await createAllDay();const record=service.list()[0];expect(record.source).toBe('MANUAL');expect(record.timeKind).toBe('ALL_DAY');expect(screen.getByText('状態: 予定')).toBeTruthy();await user.click(screen.getByRole('button',{name:'編集'}));const title=screen.getByRole('textbox',{name:'予定名'});await user.clear(title);await user.type(title,'定期診察');await user.click(screen.getByRole('button',{name:'変更を保存'}));expect(screen.getByText('定期診察')).toBeTruthy();await user.click(screen.getByRole('button',{name:'完了にする'}));expect(screen.getByText('状態: 完了')).toBeTruthy();await user.click(screen.getByRole('button',{name:'予定に戻す'}));expect(screen.getByText('状態: 予定')).toBeTruthy()});
 it('creates TIMED with the selected IANA timezone and offset instants',async()=>{const user=userEvent.setup();render(<CalendarTab service={service}/>);await user.type(screen.getByRole('textbox',{name:'予定名'}),'東京会議');await user.click(screen.getByRole('radio',{name:'時刻指定'}));await user.type(screen.getByLabelText('開始日時'),'2026-08-04T09:00');await user.type(screen.getByLabelText('終了日時'),'2026-08-04T10:00');const zone=screen.getByRole('textbox',{name:'Timezone（IANA）'});await user.clear(zone);await user.type(zone,'Asia/Tokyo');await user.click(screen.getByRole('button',{name:'予定を作成'}));const record=service.list()[0];expect(record.timeKind).toBe('TIMED');if(record.timeKind==='TIMED'){expect(record.startsAt).toBe('2026-08-04T09:00:00+09:00');expect(record.timeZone).toBe('Asia/Tokyo')}});
 it('requires a named dialog and a separate enabled confirm, supports keyboard, and restores focus on cancel',async()=>{const user=await createAllDay('歯科');const article=screen.getByText('歯科').closest('article')!;const opener=within(article).getByRole('button',{name:'削除'});opener.focus();await user.keyboard('[Enter]');expect(screen.getByRole('dialog',{name:'「歯科」を削除しますか？'})).toBeTruthy();expect(service.list()).toHaveLength(1);await user.click(screen.getByRole('button',{name:'キャンセル'}));await waitFor(()=>expect(document.activeElement).toBe(opener));await user.click(opener);const confirm=screen.getByRole('button',{name:'削除を確定する'});await waitFor(()=>expect((confirm as HTMLButtonElement).disabled).toBe(false));await user.click(confirm);expect(service.list()).toHaveLength(0)});
 it('retains the rendered records on repository refresh failure and reports the failure',async()=>{await createAllDay('保持する予定');const spy=vi.spyOn(service,'list').mockImplementation(()=>{throw new Error('storage failed')});await userEvent.click(screen.getByRole('button',{name:'完了にする'}));expect(screen.getByText('保持する予定')).toBeTruthy();expect(screen.getByRole('alert').textContent).toContain('保持されています');spy.mockRestore()});
});
