import { describe, expect, it } from 'vitest';
import { applyCalendarCommitOutcome, beginCalendarCommit, closeCommittedCalendarReceipt, dismissCalendarReceipt, calendarCandidateFingerprint, emptyCalendarCaptureState, initialCalendarCaptureDraft, rejectCalendarCandidate, startCalendarCapture, type CalendarCaptureState } from '../src/features/conversation/calendar/calendarCapture.ts';
import { executeCalendarCaptureCommit } from '../src/features/conversation/calendar/calendarCaptureCommitExecutor.ts';
import { CalendarCaptureCommitAdapter } from '../src/features/conversation/calendar/calendarCaptureCommitAdapter.ts';

const ready = (): CalendarCaptureState => ({ generation: 3, flow: null, rejectedFingerprints: [], candidate: { id:'c3', fingerprint:'fp', sourceExcerpt:'予定を追加したい', capturedAt:'2026-08-03T00:00:00Z', draft:{...initialCalendarCaptureDraft('2026-08-04','Asia/Tokyo'),title:'診察',timeKind:'ALL_DAY'}, status:'READY', attempt:0 } });
describe('calendar capture lifecycle and adapter',()=>{
  it('keys suppression to canonical candidate content, not the opening phrase',()=>{ const a=ready(), rejected=rejectCalendarCandidate(a); expect(rejected.rejectedFingerprints).toEqual(['fp']); const other={...a.candidate!.draft,title:'別の予定'}; expect(calendarCandidateFingerprint(other)).not.toBe('fp'); expect(startCalendarCapture(rejected,'予定を追加したい','2026-08-03T01:00:00Z',other).flow).not.toBeNull(); expect(emptyCalendarCaptureState().rejectedFingerprints).toEqual([]); });
  it('issues one immutable attempt and ignores stale outcomes after reset/new generation',()=>{ const begun=beginCalendarCommit(ready()); expect(beginCalendarCommit(begun.state).request).toBeUndefined(); const reset=emptyCalendarCaptureState(); const record={...begun.request!.input,id:'event' as never,status:'PLANNED' as const,revision:1,createdAt:'2026-08-03T00:01:00Z',updatedAt:'2026-08-03T00:01:00Z'}; expect(applyCalendarCommitOutcome(reset,begun.request!,{ok:true,record})).toBe(reset); });
  it('turns thrown, rejected, and invalid application outcomes into FAILED outcomes',async()=>{ for(const implementation of [()=>{throw new Error('x')},()=>Promise.reject(new Error('x')),()=>undefined] as never[]){ const adapter=new CalendarCaptureCommitAdapter({create:implementation} as never); await expect(adapter.commit(beginCalendarCommit(ready()).request!)).resolves.toMatchObject({ok:false}); } });
  it('sets consent at the save boundary rather than candidate creation',()=>{ const begun=beginCalendarCommit(ready()); expect(ready().candidate).not.toHaveProperty('consentedAt'); expect(begun.request!.input.source==='CONVERSATION_CAPTURE' && begun.request!.input.conversationProvenance.consentedAt).toBeTruthy(); });
  it('normalizes an untrusted callback synchronous throw, rejection, and invalid outcome',async()=>{ const request=beginCalendarCommit(ready()).request!; for(const callback of [()=>{throw new Error('sync')},()=>Promise.reject(new Error('reject')),()=>({unexpected:true})]) await expect(executeCalendarCaptureCommit(request,callback)).resolves.toMatchObject({ok:false}); });
  it('keeps FAILED Candidate and permits a single retry attempt',()=>{ const begun=beginCalendarCommit(ready()); const failed=applyCalendarCommitOutcome(begun.state,begun.request!,{ok:false,message:'failed'}); expect(failed.candidate?.status).toBe('FAILED'); const retry=beginCalendarCommit(failed); expect(retry.request?.attempt).toBe(2); expect(beginCalendarCommit(retry.state).request).toBeUndefined(); });
  it('closes only a COMMITTED receipt and ignores unrelated record changes',()=>{ const begun=beginCalendarCommit(ready()), now=new Date(Date.parse(begun.request!.input.conversationProvenance.consentedAt)+1).toISOString(), record={...begun.request!.input,id:'event' as never,status:'PLANNED' as const,revision:1,createdAt:now,updatedAt:now}; const committed=applyCalendarCommitOutcome(begun.state,begun.request!,{ok:true,record}); expect(dismissCalendarReceipt(committed,'unrelated')).toBe(committed); expect(closeCommittedCalendarReceipt(committed).candidate).toBeNull(); expect(closeCommittedCalendarReceipt(ready())).toEqual(ready()); });
});
