import { useState, type FormEvent } from 'react';
import { availableTimeZones } from '../../calendar/components/calendarDateTime.ts';
import type { CalendarCaptureDraft, CalendarCaptureState } from '../calendar/calendarCapture.ts';

export function CalendarCaptureCard({ capture, onAnswer, onConfirm, onBeginEdit, onApplyEdit, onReject, onCancel, onCommit, onNavigate, onDismissReceipt }: { capture: CalendarCaptureState; onAnswer: (draft: CalendarCaptureDraft) => string | undefined; onConfirm: () => void; onBeginEdit: () => void; onApplyEdit: (draft: CalendarCaptureDraft) => string | undefined; onReject: () => void; onCancel: () => void; onCommit: () => void; onNavigate: (receipt: { recordId: string; targetDate: string }) => void; onDismissReceipt: () => void }) {
  const source = capture.flow?.draft ?? capture.candidate?.draft;
  const [draft, setDraft] = useState<CalendarCaptureDraft>(() => structuredClone(source!));
  const [error, setError] = useState('');
  const flow = capture.flow, candidate = capture.candidate;
  if (flow) {
    const submit = (event: FormEvent) => { event.preventDefault(); const result = onAnswer(draft); setError(result ?? ''); };
    const label = { TITLE:'予定名は何ですか？', NOTE:'メモはありますか？（空欄でも進めます）', TIME_KIND:'終日と時刻指定のどちらですか？', START_DATE:'開始日はいつですか？', END_DATE:'終了日はいつですか？', STARTS_AT:'開始日時はいつですか？', ENDS_AT:'終了日時はいつですか？', TIME_ZONE:'タイムゾーンを選んでください。' }[flow.step];
    return <form className="capture-review" onSubmit={submit}><h3>予定を一つずつ確認</h3><label>{label}{flow.step === 'TITLE' ? <input autoFocus value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/> : flow.step === 'NOTE' ? <textarea autoFocus value={draft.note} onChange={e=>setDraft({...draft,note:e.target.value})}/> : flow.step === 'TIME_KIND' ? <select autoFocus value={draft.timeKind} onChange={e=>setDraft({...draft,timeKind:e.target.value as CalendarCaptureDraft['timeKind']})}><option value="">選択してください</option><option value="ALL_DAY">終日</option><option value="TIMED">時刻指定</option></select> : flow.step === 'START_DATE' || flow.step === 'END_DATE' ? <input autoFocus type="date" value={flow.step === 'START_DATE' ? draft.startDate : draft.endDate} onChange={e=>setDraft({...draft,[flow.step === 'START_DATE'?'startDate':'endDate']:e.target.value})}/> : flow.step === 'TIME_ZONE' ? <select autoFocus value={draft.timeZone} onChange={e=>setDraft({...draft,timeZone:e.target.value})}>{availableTimeZones(draft.timeZone).map(z=><option key={z}>{z}</option>)}</select> : <input autoFocus type="datetime-local" value={flow.step === 'STARTS_AT'?draft.startsAt:draft.endsAt} onChange={e=>setDraft({...draft,[flow.step === 'STARTS_AT'?'startsAt':'endsAt']:e.target.value})}/>}</label>{error && <p role="alert">{error}</p>}<button type="submit">次へ</button><button type="button" onClick={onCancel}>この追加をやめる</button></form>;
  }
  if (!candidate) return null;
  if (candidate.status === 'COMMITTED' && candidate.receipt) return <section className="capture-review" aria-label="カレンダー保存結果"><h3>予定を保存しました</h3><p>保存先: Calendar</p><button type="button" onClick={() => onNavigate(candidate.receipt!)}>Calendarでこの予定を見る</button><button type="button" onClick={onDismissReceipt}>閉じる</button></section>;
  if (candidate.status === 'EDITING') return <form className="capture-review" onSubmit={e=>{e.preventDefault(); setError(onApplyEdit(draft) ?? '');}}><h3>Candidateを修正</h3><label>予定名<input required value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>メモ<textarea value={draft.note} onChange={e=>setDraft({...draft,note:e.target.value})}/></label><fieldset><legend>予定の種類</legend><label><input type="radio" checked={draft.timeKind==='ALL_DAY'} onChange={()=>setDraft({...draft,timeKind:'ALL_DAY'})}/>終日</label><label><input type="radio" checked={draft.timeKind==='TIMED'} onChange={()=>setDraft({...draft,timeKind:'TIMED'})}/>時刻指定</label></fieldset>{draft.timeKind === 'ALL_DAY' ? <><label>開始日<input type="date" value={draft.startDate} onChange={e=>setDraft({...draft,startDate:e.target.value})}/></label><label>終了日<input type="date" value={draft.endDate} onChange={e=>setDraft({...draft,endDate:e.target.value})}/></label></> : <><label>開始日時<input type="datetime-local" value={draft.startsAt} onChange={e=>setDraft({...draft,startsAt:e.target.value})}/></label><label>終了日時<input type="datetime-local" value={draft.endsAt} onChange={e=>setDraft({...draft,endsAt:e.target.value})}/></label><label>タイムゾーン<select value={draft.timeZone} onChange={e=>setDraft({...draft,timeZone:e.target.value})}>{availableTimeZones(draft.timeZone).map(z=><option key={z}>{z}</option>)}</select></label></>}{error && <p role="alert">{error}</p>}<button type="submit">修正内容を適用</button></form>;
  return <section className="capture-review" tabIndex={-1} aria-label="カレンダー保存候補"><h3>Calendar専用Candidate</h3><p>保存先: Calendar</p><p>日時: {candidate.draft.timeKind === 'ALL_DAY' ? `${candidate.draft.startDate}〜${candidate.draft.endDate}（終日）` : `${candidate.draft.startsAt}〜${candidate.draft.endsAt} (${candidate.draft.timeZone})`}</p><p>入力元: 本人による構造化入力</p><p>元の発言: {candidate.sourceExcerpt}</p><p>状態: {candidate.status === 'FAILED' ? '保存失敗・未保存' : candidate.status === 'COMMITTING' ? '保存中' : '未保存'}</p><p>予定名: {candidate.draft.title}</p>{candidate.failure && <p role="alert">保存できませんでした。候補を保持しています。再試行できます。</p>}<div className="capture-review-actions">{candidate.status === 'PROPOSED' && <button type="button" onClick={onConfirm}>この内容を確認する</button>}<button type="button" disabled={candidate.status === 'COMMITTING'} onClick={onBeginEdit}>候補を修正する</button>{(candidate.status === 'READY'||candidate.status === 'FAILED') && <button type="button" onClick={onCommit}>{candidate.status === 'FAILED'?'保存を再試行':'この内容で保存'}</button>}<button type="button" disabled={candidate.status === 'COMMITTING'} onClick={onReject}>保存しない</button></div></section>;
}
