import { useEffect, useRef, useState } from 'react';
import type { CaptureCandidate, CaptureCommitRequest, DailyLogCapturePayload } from '../types/captureCandidate.ts';
import { presentCaptureCandidateReview } from './captureCandidatePresentation.ts';
type Props = { candidate: CaptureCandidate; onBeginEdit:()=>void; onApplyEdit:(p:DailyLogCapturePayload)=>string[]|undefined; onMarkReady:()=>string[]|undefined; onReject:()=>void; onCancel:()=>void; onRequestCommit:()=>CaptureCommitRequest|undefined };
export function CaptureCandidateReviewCard({candidate,onBeginEdit,onApplyEdit,onMarkReady,onReject,onCancel,onRequestCommit}:Props) {
 const model=presentCaptureCandidateReview(candidate), [payload,setPayload]=useState(candidate.proposedPayload), [errors,setErrors]=useState<string[]>([]); const dateRef=useRef<HTMLInputElement>(null), moodRef=useRef<HTMLInputElement>(null), fatigueRef=useRef<HTMLInputElement>(null);
 useEffect(()=>{if(candidate.status==='EDITING') dateRef.current?.focus()},[candidate.status]);
 const focusError=(next:string[])=>{if(next.includes('INVALID_TARGET_DATE')||next.includes('PAYLOAD_DATE_MISMATCH'))dateRef.current?.focus();else if(next.includes('INVALID_MOOD'))moodRef.current?.focus();else if(next.includes('INVALID_FATIGUE'))fatigueRef.current?.focus()};
 const apply=()=>{const next=onApplyEdit(payload)??[];setErrors(next);focusError(next)}, ready=()=>{const next=onMarkReady()??[];setErrors(next);focusError(next)}, editing=candidate.status==='EDITING';
 return <article className="capture-review" aria-labelledby={`capture-title-${candidate.id}`}><header><p className="capture-review-destination">保存先: 日々の記録</p><h3 id={`capture-title-${candidate.id}`}>保存する内容を確認</h3></header><p className="capture-review-status" role="status" aria-live="polite">{model.statusLabel}</p>{model.isUnsaved&&<p className="capture-review-unsaved">この内容はまだ保存されていません。</p>}{candidate.failure&&<p className="capture-review-error" role="alert">{candidate.failure.message}</p>}<dl className="capture-review-meta"><div><dt>保存目的</dt><dd>{candidate.purpose}</dd></div><div><dt>対象日</dt><dd>{candidate.targetDate}</dd></div></dl>
 {editing?<div className="capture-review-fields"><label htmlFor={`capture-date-${candidate.id}`}>対象日</label><input ref={dateRef} id={`capture-date-${candidate.id}`} type="date" value={payload.date} aria-invalid={errors.includes('INVALID_TARGET_DATE')} aria-describedby={errors.includes('INVALID_TARGET_DATE')?`capture-date-error-${candidate.id}`:undefined} onChange={e=>setPayload({...payload,date:e.target.value as DailyLogCapturePayload['date']})}/>{errors.includes('INVALID_TARGET_DATE')&&<span id={`capture-date-error-${candidate.id}`} className="capture-field-error">正しい日付を入力してください。</span>}<label htmlFor={`capture-mood-${candidate.id}`}>mood（1〜5、本人明示値）</label><input ref={moodRef} id={`capture-mood-${candidate.id}`} type="number" min="1" max="5" value={payload.mood.value??''} aria-invalid={errors.includes('INVALID_MOOD')} aria-describedby={errors.includes('INVALID_MOOD')?`capture-mood-error-${candidate.id}`:undefined} onChange={e=>setPayload({...payload,mood:{value:e.target.value===''?null:Number(e.target.value) as 1|2|3|4|5,origin:'USER_EXPLICIT'}})}/>{errors.includes('INVALID_MOOD')&&<span id={`capture-mood-error-${candidate.id}`} className="capture-field-error">1〜5のmoodを入力してください。</span>}<label htmlFor={`capture-fatigue-${candidate.id}`}>fatigue（1〜5、本人明示値）</label><input ref={fatigueRef} id={`capture-fatigue-${candidate.id}`} type="number" min="1" max="5" value={payload.fatigue.value??''} aria-invalid={errors.includes('INVALID_FATIGUE')} aria-describedby={errors.includes('INVALID_FATIGUE')?`capture-fatigue-error-${candidate.id}`:undefined} onChange={e=>setPayload({...payload,fatigue:{value:e.target.value===''?null:Number(e.target.value) as 1|2|3|4|5,origin:'USER_EXPLICIT'}})}/>{errors.includes('INVALID_FATIGUE')&&<span id={`capture-fatigue-error-${candidate.id}`} className="capture-field-error">1〜5のfatigueを入力してください。</span>}<p className="capture-scale-help">{model.fatigueHelp}</p><label htmlFor={`capture-note-${candidate.id}`}>note</label><textarea id={`capture-note-${candidate.id}`} value={payload.note} onChange={e=>setPayload({...payload,note:e.target.value})}/><label htmlFor={`capture-events-${candidate.id}`}>events（1行に1件）</label><textarea id={`capture-events-${candidate.id}`} value={payload.events.join('\n')} onChange={e=>setPayload({...payload,events:e.target.value.split('\n')})}/></div>:<dl className="capture-review-values"><div><dt>mood</dt><dd>{candidate.proposedPayload.mood.value??'未入力'}（{model.originLabel}）</dd></div><div><dt>fatigue</dt><dd>{candidate.proposedPayload.fatigue.value??'未入力'}（{model.originLabel}）<small>{model.fatigueHelp}</small></dd></div><div><dt>note</dt><dd>{candidate.proposedPayload.note||'なし'}</dd></div><div><dt>events</dt><dd>{candidate.proposedPayload.events.length?<ul>{candidate.proposedPayload.events.map((event,i)=><li key={`${event}-${i}`}>{event}</li>)}</ul>:'なし'}</dd></div></dl>}
 <section className="capture-review-source" aria-labelledby={`capture-source-${candidate.id}`}><h4 id={`capture-source-${candidate.id}`}>本人に提示する会話からの引用</h4><blockquote>{candidate.sourceExcerpt}</blockquote></section><div className="capture-review-actions">{editing?<><button type="button" onClick={apply}>修正を適用する</button><button type="button" onClick={ready}>この内容を確認する</button><button type="button" onClick={onCancel}>取消</button></>:<><button type="button" disabled={model.controlsDisabled||candidate.status==='COMMITTED'} onClick={onBeginEdit}>修正する</button><button type="button" disabled={!model.saveAllowed} onClick={onRequestCommit}>保存する</button><button type="button" disabled={model.controlsDisabled||candidate.status==='COMMITTED'} onClick={onReject}>今回は保存しない</button></>}</div></article>
}
