/* eslint-disable react-hooks/set-state-in-effect */
import { useEffect, useRef, useState, type FormEvent } from 'react';
import type { CalendarEventId, CalendarEventRecord, CorrectCalendarEventInput } from '../types/calendarEvent.ts';
import { calendarEventApplicationService as defaultService } from '../services/compositionRoot.ts';
import type { CalendarEventApplicationService } from '../services/calendarEventApplicationService.ts';
import { instantToLocalDateTime, localDateTimeToOffsetInstant } from './calendarDateTime.ts';
import './CalendarTab.css';
type Draft={title:string;note:string;timeKind:'ALL_DAY'|'TIMED';startDate:string;endDate:string;startsAt:string;endsAt:string;timeZone:string};
const today=()=>new Date().toISOString().slice(0,10); const blank=():Draft=>({title:'',note:'',timeKind:'ALL_DAY',startDate:today(),endDate:today(),startsAt:'',endsAt:'',timeZone:Intl.DateTimeFormat().resolvedOptions().timeZone||'UTC'});
const labels={PLANNED:'予定',COMPLETED:'完了',CANCELLED:'取消'} as const;
export function CalendarTab({service=defaultService}:{service?:CalendarEventApplicationService}){
 const [records,setRecords]=useState<CalendarEventRecord[]>([]),[draft,setDraft]=useState(blank),[editing,setEditing]=useState<CalendarEventId|null>(null),[deleting,setDeleting]=useState<CalendarEventRecord|null>(null),[message,setMessage]=useState(''); const [ready,setReady]=useState(false); const opener=useRef<HTMLButtonElement|null>(null),heading=useRef<HTMLHeadingElement|null>(null);
 const load=()=>{try{setRecords(service.list());setMessage('');return true}catch{setMessage('予定を読み込めませんでした。表示中の予定は保持されています。');return false}};
 useEffect(()=>{load()},[service]); // eslint-disable-line react-hooks/exhaustive-deps
 useEffect(()=>{if(!deleting)return;setReady(false);const id=setTimeout(()=>setReady(true),0);return()=>clearTimeout(id)},[deleting]);
 const makeInput=():CorrectCalendarEventInput|null=>{const common={title:draft.title.trim(),note:draft.note.trim()||undefined};if(draft.timeKind==='ALL_DAY')return{...common,timeKind:'ALL_DAY',startDate:draft.startDate,endDate:draft.endDate};const startsAt=localDateTimeToOffsetInstant(draft.startsAt,draft.timeZone),endsAt=localDateTimeToOffsetInstant(draft.endsAt,draft.timeZone);return startsAt&&endsAt?{...common,timeKind:'TIMED',startsAt,endsAt,timeZone:draft.timeZone}:null};
 const submit=(e:FormEvent)=>{e.preventDefault();const input=makeInput();if(!input){setMessage('日時とIANA timezoneを確認してください。夏時間で存在しない・重複する時刻は保存できません。');return}const result=editing?service.correct(editing,input):service.create({...input,source:'MANUAL'});if(!result.ok){setMessage('予定を保存できませんでした。既存の予定は保持されています。入力内容を確認してください。');return}setDraft(blank());setEditing(null);load();heading.current?.focus()};
 const edit=(r:CalendarEventRecord)=>{setEditing(r.id);setDraft(r.timeKind==='ALL_DAY'?{...blank(),title:r.title,note:r.note??'',startDate:r.startDate,endDate:r.endDate}:{...blank(),title:r.title,note:r.note??'',timeKind:'TIMED',startsAt:instantToLocalDateTime(r.startsAt,r.timeZone),endsAt:instantToLocalDateTime(r.endsAt,r.timeZone),timeZone:r.timeZone});heading.current?.focus()};
 const status=(r:CalendarEventRecord,a:'complete'|'cancel'|'reopen')=>{if(!service[a](r.id).ok){setMessage('状態を変更できませんでした。既存の予定は保持されています。');return}load()};
 const close=()=>{setDeleting(null);requestAnimationFrame(()=>opener.current?.focus())}; const remove=()=>{if(!deleting||!ready)return;const result=service.delete(deleting.id);setDeleting(null);if(!result.ok){setMessage('予定を削除できませんでした。既存の予定は保持されています。');requestAnimationFrame(()=>opener.current?.focus());return}load();heading.current?.focus()};
 return <section className="calendar" aria-labelledby="calendar-heading"><h2 id="calendar-heading" ref={heading} tabIndex={-1}>カレンダー</h2><p>手入力の予定を管理します。会話からの予定保存はまだ利用できません。</p>{message&&<p role="alert" className="calendar-alert">{message}</p>}
 <form className="calendar-form" onSubmit={submit}><h3>{editing?'予定を編集':'予定を作成'}</h3><label>予定名<input required value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>メモ（任意）<textarea value={draft.note} onChange={e=>setDraft({...draft,note:e.target.value})}/></label><fieldset><legend>予定の種類</legend><label><input type="radio" checked={draft.timeKind==='ALL_DAY'} onChange={()=>setDraft({...draft,timeKind:'ALL_DAY'})}/>終日</label><label><input type="radio" checked={draft.timeKind==='TIMED'} onChange={()=>setDraft({...draft,timeKind:'TIMED'})}/>時刻指定</label></fieldset>
 {draft.timeKind==='ALL_DAY'?<div className="calendar-fields"><label>開始日<input required type="date" value={draft.startDate} onChange={e=>setDraft({...draft,startDate:e.target.value})}/></label><label>終了日<input required type="date" value={draft.endDate} onChange={e=>setDraft({...draft,endDate:e.target.value})}/></label></div>:<><div className="calendar-fields"><label>開始日時<input required type="datetime-local" value={draft.startsAt} onChange={e=>setDraft({...draft,startsAt:e.target.value})}/></label><label>終了日時<input required type="datetime-local" value={draft.endsAt} onChange={e=>setDraft({...draft,endsAt:e.target.value})}/></label></div><label>Timezone（IANA）<input required placeholder="Asia/Tokyo" value={draft.timeZone} onChange={e=>setDraft({...draft,timeZone:e.target.value})}/></label></>}
 <div className="calendar-actions"><button type="submit">{editing?'変更を保存':'予定を作成'}</button>{editing&&<button type="button" onClick={()=>{setEditing(null);setDraft(blank())}}>編集をやめる</button>}</div><small>予定は削除するまで保持されます。バックアップとして書き出したコピーは、アプリ内で削除しても消えません。</small></form>
 <div className="calendar-list" aria-live="polite">{records.length===0?<p>予定はまだありません。</p>:records.map(r=><article key={r.id} className={`calendar-event status-${r.status.toLowerCase()}`} tabIndex={-1}><header><h3>{r.title}</h3><strong className="calendar-status">状態: {labels[r.status]}</strong></header><p>{r.timeKind==='ALL_DAY'?`終日: ${r.startDate}〜${r.endDate}`:`時刻指定: ${instantToLocalDateTime(r.startsAt,r.timeZone)}〜${instantToLocalDateTime(r.endsAt,r.timeZone)} (${r.timeZone})`}</p>{r.note&&<p>{r.note}</p>}<div className="calendar-actions"><button type="button" onClick={()=>edit(r)}>編集</button>{r.status==='PLANNED'?<><button type="button" onClick={()=>status(r,'complete')}>完了にする</button><button type="button" onClick={()=>status(r,'cancel')}>取消にする</button></>:<button type="button" onClick={()=>status(r,'reopen')}>予定に戻す</button>}<button type="button" onClick={e=>{opener.current=e.currentTarget;setDeleting(r)}}>削除</button></div></article>)}</div>
 {deleting&&<div className="calendar-dialog-backdrop"><div role="dialog" aria-modal="true" aria-labelledby="calendar-delete-title" className="calendar-dialog"><h3 id="calendar-delete-title">「{deleting.title}」を削除しますか？</h3><p>この予定を削除します。状態を「取消」にする操作とは異なり、元に戻せません。</p><div className="calendar-actions"><button type="button" onClick={close}>キャンセル</button><button type="button" disabled={!ready} autoFocus onClick={remove}>削除を確定する</button></div></div></div>}</section>
}
