import assert from 'node:assert/strict';
import { createUnderstandingId, createUnderstandingObject } from '../src/features/understanding/factories/understandingObjectFactory.ts';
import { UnderstandingObjectApplicationService } from '../src/features/understanding/services/understandingObjectApplicationService.ts';
import { LocalStorageUnderstandingCandidateRepository } from '../src/features/understanding/services/localStorageUnderstandingCandidateRepository.ts';
import { LocalStorageUnderstandingCandidateResponseRepository } from '../src/features/understanding/services/localStorageUnderstandingCandidateResponseRepository.ts';
import { LocalStorageUnderstandingObjectRepository, UNDERSTANDING_OBJECT_STORAGE_KEY } from '../src/features/understanding/services/localStorageUnderstandingObjectRepository.ts';
import type { Evidence, EvidenceId } from '../src/features/analysis/types/evidence.ts';
import type { DateString, EntryId } from '../src/features/daily-log/types/log.ts';
import type { SleepRecordId } from '../src/features/sleep/types/sleepRecord.ts';
import type { UnderstandingCandidate, UnderstandingCandidateAnswer, UnderstandingCandidateId, UnderstandingCandidateResponse } from '../src/features/understanding/types/understandingCandidate.ts';
import type { UnderstandingObject } from '../src/features/understanding/types/understandingObject.ts';

class MemoryStorage implements Storage { private values = new Map<string, string>(); get length() { return this.values.size; } clear() { this.values.clear(); } getItem(k: string) { return this.values.get(k) ?? null; } key(i: number) { return [...this.values.keys()][i] ?? null; } removeItem(k: string) { this.values.delete(k); } setItem(k: string, v: string) { this.values.set(k, v); } }
const now = '2026-07-22T00:00:00.000Z';
const evidence = (id: string, confidence: number): Evidence => ({ id: id as EvidenceId, type: 'SLEEP_FATIGUE_OBSERVATION', analyzerId: 'sleep-fatigue-analyzer', title: `Evidence ${id}`, message: '睡眠と疲労の観測です。', observation: '短時間睡眠の日に疲労が高い傾向が観測されました。', confidence, sampleSize: 4, sourceReferences: [{ sourceType: 'daily_log', id: 'log-1' as EntryId, date: '2026-07-01' as DateString }, { sourceType: 'sleep_record', id: 'sleep-1' as SleepRecordId, date: '2026-07-01' as DateString }], period: { from: '2026-07-01' as DateString, to: '2026-07-04' as DateString }, createdAt: now, dedupeKey: `evidence:${id}` });
const e1 = evidence('evidence-1', 0.7); const e2 = evidence('evidence-2', 0.8); const e3 = evidence('evidence-3', 2);
const candidate: UnderstandingCandidate = { id: 'candidate-1' as UnderstandingCandidateId, type: 'SLEEP_FATIGUE_PATTERN', generatorId: 'sleep-fatigue-candidate-generator', title: '睡眠と疲労の関係', statement: '睡眠が短い日は疲労を感じやすい傾向があるかもしれません。', explanation: 'Evidenceから作りました。', evidenceIds: [e1.id, e2.id, e2.id], dedupeKey: 'sleep-fatigue:evidence-1', createdAt: now, updatedAt: now };
const response = (answer: UnderstandingCandidateAnswer, id = candidate.id): UnderstandingCandidateResponse => ({ candidateId: id, answer, respondedAt: now });

const created = createUnderstandingObject(candidate, response('AGREE'), [e1, e2], now);
assert.equal(created.ok, true, 'AGREEからObjectを生成できる');
if (!created.ok) throw new Error('expected object');
assert.equal(createUnderstandingObject(candidate, response('PARTIALLY_DISAGREE'), [e1, e2], now).ok, false, 'PARTIALLY_DISAGREEから生成しない');
assert.equal(createUnderstandingObject(candidate, response('UNSURE'), [e1, e2], now).ok, false, 'UNSUREから生成しない');
assert.equal(createUnderstandingObject(candidate, response('AGREE', 'other' as UnderstandingCandidateId), [e1, e2], now).ok, false, 'candidate mismatchで生成しない');
assert.equal(created.object.type, 'SLEEP_FATIGUE_RELATIONSHIP');
assert.equal(created.object.layer, 'LONG_TERM');
assert.deepEqual(created.object.categories, ['INTERNAL_STATE', 'BEHAVIOR']);
assert.equal(created.object.status.maturity, 'HYPOTHESIS');
assert.equal(created.object.statement, candidate.statement);
assert.deepEqual(created.object.sourceCandidateIds, [candidate.id]);
assert.deepEqual(created.object.evidenceIds, [e1.id, e2.id]);
assert.equal(createUnderstandingObject({ ...candidate, evidenceIds: [] }, response('AGREE'), [e1], now).ok, false, 'Evidence不足で生成しない');
assert.equal(createUnderstandingObject(candidate, response('AGREE'), [e1], now).ok, false, '一部Evidenceしか解決できない場合も生成しない');
assert.equal(created.object.id, createUnderstandingId('SLEEP_FATIGUE_RELATIONSHIP', candidate.dedupeKey));
assert.equal(created.object.id, createUnderstandingObject(candidate, response('AGREE'), [e1, e2], now).ok && createUnderstandingObject(candidate, response('AGREE'), [e1, e2], now).object.id, '同じ入力で同じIDになる');
assert.equal(created.object.status.confidence, 0.75, 'confidenceがEvidence平均になる');
const clamped = createUnderstandingObject({ ...candidate, evidenceIds: [e1.id, e3.id] }, response('AGREE'), [e1, e3], now);
assert.equal(clamped.ok && clamped.object.status.confidence, 0.85, 'confidenceが0〜1へclampされる');
assert.equal(created.object.status.evidenceCount, 2);
assert.deepEqual(created.object.status.nextQuestions, []);
assert.equal('confidence' in created.object, false, 'confidenceはObject直下に存在しない');

const storage = new MemoryStorage(); storage.setItem('compass_user_model', 'sentinel');
const repo = new LocalStorageUnderstandingObjectRepository(storage); repo.save(created.object);
assert.equal(new LocalStorageUnderstandingObjectRepository(storage).list().length, 1, 'save / reload');
const learned: UnderstandingObject = { ...created.object, status: { ...created.object.status, maturity: 'LEARNED' }, createdAt: 'old', updatedAt: 'old' };
repo.save(learned); repo.save({ ...created.object, sourceCandidateIds: [...created.object.sourceCandidateIds, candidate.id], evidenceIds: [e1.id], updatedAt: 'new' });
const merged = repo.list()[0];
assert.equal(repo.list().length, 1, 'idによるupsert');
assert.equal(merged.createdAt, now, 'createdAt維持');
assert.deepEqual(merged.sourceCandidateIds, [candidate.id], 'sourceCandidateIds重複排除');
assert.deepEqual(merged.evidenceIds.sort(), [e1.id, e2.id].sort(), 'evidenceIds重複排除');
assert.equal(merged.status.evidenceCount, 2, 'evidenceCount整合');
assert.equal(merged.status.maturity, 'LEARNED', 'maturityを降格させない');
storage.setItem(UNDERSTANDING_OBJECT_STORAGE_KEY, '{bad'); assert.deepEqual(repo.list(), [], 'invalid JSONでクラッシュしない');
storage.setItem(UNDERSTANDING_OBJECT_STORAGE_KEY, JSON.stringify([created.object, { bad: true }])); assert.equal(repo.list().length, 1, '配列内の不正要素だけを除外する');
assert.equal(repo.getBySourceCandidateId(candidate.id)?.id, created.object.id, 'getBySourceCandidateIdできる'); repo.delete(created.object.id); assert.equal(repo.list().length, 0, 'deleteできる');

const candidateRepo = new LocalStorageUnderstandingCandidateRepository(storage); const responseRepo = new LocalStorageUnderstandingCandidateResponseRepository(storage); const objectRepo = new LocalStorageUnderstandingObjectRepository(storage); const app = new UnderstandingObjectApplicationService(candidateRepo, responseRepo, objectRepo);
candidateRepo.save(candidate); responseRepo.save(response('AGREE')); assert.equal(app.reconcileCandidate(candidate.id, [e1, e2], now).action, 'CREATED_OR_UPDATED', 'AGREE ResponseからObjectを保存できる');
app.reconcileCandidate(candidate.id, [e1, e2], now); assert.equal(objectRepo.list().length, 1, '複数回reconcileしても増殖しない');
responseRepo.save(response('PARTIALLY_DISAGREE')); app.reconcileCandidate(candidate.id, [e1, e2], now); assert.equal(objectRepo.list().length, 0, 'PARTIALLY_DISAGREEへ変更するとObjectが消える');
responseRepo.save(response('AGREE')); app.reconcileCandidate(candidate.id, [e1, e2], now); responseRepo.save(response('UNSURE')); app.reconcileCandidate(candidate.id, [e1, e2], now); assert.equal(objectRepo.list().length, 0, 'UNSUREへ変更するとObjectが消える');
responseRepo.save(response('AGREE')); app.reconcileCandidate(candidate.id, [e1, e2], now); assert.equal(objectRepo.list().length, 1, '非AGREEからAGREEへ変更するとObjectが作られる');
assert.equal(app.reconcileCandidate('missing', [e1], now).action, 'SKIPPED', 'Candidate不在時は作らない');
responseRepo.clear(); assert.equal(app.reconcileCandidate(candidate.id, [e1], now).action, 'SKIPPED', 'Response不在時は作らない');
responseRepo.save(response('AGREE')); objectRepo.clear(); assert.equal(app.reconcileCandidate(candidate.id, [], now).action, 'SKIPPED', 'Evidence不在時は作らない');
objectRepo.clear(); app.reconcileAll([e1, e2], now); assert.equal(objectRepo.list().length, 1, 'reconcileAllで既存AGREE Responseをbackfillできる');
assert.equal(storage.getItem('compass_user_model'), 'sentinel', 'UserModel storage is unchanged');
console.log('Understanding Object tests passed');
