/* eslint-disable @typescript-eslint/no-explicit-any */
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { BackupApplicationService, type BackupEnvelope } from '../src/features/backup/services/backupApplicationService.ts';
import { BACKUP_RESOURCE_REGISTRY } from '../src/features/backup/services/backupResourceRegistry.ts';
import { LocalStorageInsightRepository } from '../src/features/analysis/services/localStorageInsightRepository.ts';
import { LocalStorageLogRepository } from '../src/features/daily-log/services/localStorageLogRepository.ts';
import { LocalStorageUserModelUpdateCandidateRepository } from '../src/features/compass-map/services/userModelUpdateCandidateService.ts';

class MemoryStorage { readonly values = new Map<string, string>(); failOnceOnKey: string | null = null; getItem(k:string){return this.values.get(k)??null} removeItem(k:string){this.values.delete(k)} setItem(k:string,v:string){if(k===this.failOnceOnKey){this.failOnceOnKey=null;throw Error('write failure')}this.values.set(k,v)} }
const t='2026-07-30T00:00:00.000Z';
const evidence={id:'evidence-1',type:'SLEEP_FATIGUE_OBSERVATION',analyzerId:'analyzer',title:'title',message:'message',observation:'observation',confidence:.7,sampleSize:2,sourceReferences:[{sourceType:'daily_log',id:'log-1',date:'2026-07-29'}],period:{from:'2026-07-29',to:'2026-07-29'},createdAt:t,dedupeKey:'evidence-key'};
const candidate={id:'candidate-1',type:'SLEEP_FATIGUE_PATTERN',generatorId:'generator',title:'title',statement:'statement',explanation:'explanation',evidenceIds:['evidence-1'],dedupeKey:'candidate-key',createdAt:t,updatedAt:t};
const object={id:'object-1',type:'SLEEP_FATIGUE_RELATIONSHIP',layer:'LONG_TERM',categories:['INTERNAL_STATE'],statement:'statement',sourceCandidateIds:['candidate-1'],evidenceIds:['evidence-1'],status:{maturity:'HYPOTHESIS',confidence:.7,evidenceCount:1,lastUpdatedAt:t,nextQuestions:[]},createdAt:t,updatedAt:t};
const evidenceRef={sourceType:'daily_log',logId:'log-1',analyzerId:'analyzer',rationale:'reason',excerpt:'text',sourceCreatedAt:t};
const hypothesis={value:[],confidence:0,evidenceList:[],lastUpdated:t};
const location={schemaVersion:1,id:'location-1',displayName:'東京',municipality:'東京',countryCode:'JP',timezone:'Asia/Tokyo',coordinates:{latitude:35,longitude:139},source:'USER_CONFIRMED',confirmationStatus:'CONFIRMED',createdAt:t,updatedAt:t};
const weatherLocation={timezone:'Asia/Tokyo',precision:'COARSE',locality:'東京',countryCode:'JP'};
const forecast={id:'forecast-1',schemaVersion:1,kind:'WEATHER_FORECAST_SNAPSHOT',targetPeriod:{localDate:'2026-07-30',timezone:'Asia/Tokyo',granularity:'DAILY'},forecastValues:{temperature:{value:25,unit:'celsius'}},location:weatherLocation,source:{provider:'test',sourceType:'FORECAST',fetchedAt:t},availability:{status:'AVAILABLE'},createdAt:t};
const observed={id:'observed-1',schemaVersion:1,kind:'OBSERVED_WEATHER_RECORD',observedPeriod:{localDate:'2026-07-29',timezone:'Asia/Tokyo',granularity:'DAILY'},observedValues:{temperature:{value:24,unit:'celsius'}},location:weatherLocation,source:{provider:'test',sourceType:'HISTORICAL',fetchedAt:t},availability:{status:'AVAILABLE'},createdAt:t};
const calendarEvent={id:'calendar-1',title:'大切な面談',note:'本人だけの予定メモ',timeKind:'ALL_DAY',startDate:'2026-08-04',endDate:'2026-08-04',status:'PLANNED',source:'CONVERSATION_CAPTURE',conversationProvenance:{capturedAt:t,consentedAt:t,extractorVersion:'1',sourceExcerpt:'来週、大切な面談があります'},revision:1,createdAt:t,updatedAt:t};
const fixtures: Record<string, unknown>={
 dailyLogs:[{id:'log-2',date:'2026-07-30',createdAt:t,updatedAt:t,schemaVersion:1,mood:3,fatigue:4,sleepHours:null,note:'note',events:[],captureProvenance:{source:'CONVERSATION_CAPTURE',capturedAt:t,consentedAt:t,extraction:{method:'USER_STRUCTURED_INPUT',version:'1'},sourceExcerpt:'excerpt'}},{id:'log-1',date:'2026-07-29',createdAt:t,updatedAt:t,schemaVersion:1,mood:4,fatigue:3,sleepHours:null,note:'note',events:[]}],
 calendarEvents:{schemaVersion:1,records:[calendarEvent]},
 sleepRecords:[{id:'sleep-1',sleepDate:'2026-07-29',bedtime:'2026-07-28T23:00:00.000Z',wakeTime:'2026-07-29T07:00:00.000Z',durationMinutes:480,source:'MANUAL',createdAt:t,updatedAt:t}],
 baseLocation:{schemaVersion:1,location},weatherForecastSnapshots:{schemaVersion:1,records:[forecast]},observedWeatherRecords:{schemaVersion:1,records:[observed]},evidence:[evidence],understandingCandidates:[candidate],candidateResponses:[{candidateId:'candidate-1',answer:'AGREE',respondedAt:t}],understandingObjects:[object],understandingHistory:{schemaVersion:1,records:[{id:'history-1',type:'CANDIDATE_RESPONSE_CHANGED',candidateId:'candidate-1',candidateTitle:'title',candidateStatement:'statement',previousAnswer:null,answer:'AGREE',occurredAt:t},{id:'history-2',type:'CANDIDATE_RESPONSE_CHANGED',candidateId:'candidate-1',candidateTitle:'title',candidateStatement:'statement',previousAnswer:'AGREE',answer:'UNSURE',occurredAt:'2026-07-31T00:00:00.000Z'}]},formalUserModel:{schemaVersion:1,userId:'user-1',understandingIds:{longTerm:['object-1'],shortTerm:[]},createdAt:t,updatedAt:t},
 legacyInsights:[{id:'insight-1',type:'PATTERN',message:'message',confidence:.8,analyzerId:'analyzer',evidenceSummaries:['summary'],evidenceRefs:[evidenceRef],relatedLogIds:['log-1'],dedupeKey:'insight-key',createdAt:t,updatedAt:t,status:'NEW'}],
 legacyUserModel:{userId:'user-1',longTerm:{coreValues:hypothesis,longTermGoals:hypothesis,personalityTraits:hypothesis},shortTerm:{currentMood:{status:'ok',intensity:3,lastUpdated:t},immediateConcerns:hypothesis,recentInterests:hypothesis}},
 legacyUserModelUpdateCandidates:[{id:'update-1',sourceInsightId:'insight-1',dedupeKey:'update-key',targetField:'shortTerm.immediateConcerns',proposedValue:['value'],confidence:.8,evidenceRefs:[evidenceRef],createdAt:t,status:'PENDING'}],
 legacyUserModelUpdateHistory:[{candidateId:'update-1',sourceInsightId:'insight-1',evidenceRefs:[evidenceRef],targetField:'shortTerm.immediateConcerns',appliedAt:t}],
};
function populatedStorage(){const s=new MemoryStorage();for(const d of BACKUP_RESOURCE_REGISTRY)s.setItem(d.storageKey,JSON.stringify(fixtures[d.name]));return s}
const storage=populatedStorage(); storage.setItem('not-managed','keep'); let reconciles=0;
const service=new BackupApplicationService(storage,BACKUP_RESOURCE_REGISTRY,()=>t,()=>{reconciles++});
const exported=service.export(); const envelope=JSON.parse(exported) as BackupEnvelope;
assert.equal(envelope.resources.length,16); assert.deepEqual(envelope.resources.map(r=>r.name),BACKUP_RESOURCE_REGISTRY.map(r=>r.name));
assert.doesNotMatch(JSON.stringify(envelope),/rejectedDeduplicationKeys|dailyLogNavigationTarget|activeCaptureCandidate/,'session suppression, navigation, and Capture Candidate are not exported');
assert.doesNotMatch(JSON.stringify(envelope.resources.find(r=>r.name==='dailyLogs')!.data),/sourceMessageId|candidateId|deduplicationKey/,'ephemeral capture identifiers are not exported with DailyLog');
assert.equal(BACKUP_RESOURCE_REGISTRY.some(({name,storageKey}) => /conversation/i.test(name) || /conversation/i.test(storageKey)), false, 'in-memory conversation is not a backup resource');
const exportedCalendar=(envelope.resources.find(r=>r.name==='calendarEvents')!.data as any).records[0];assert.equal(exportedCalendar.title,calendarEvent.title);assert.equal(exportedCalendar.note,calendarEvent.note);assert.equal(exportedCalendar.conversationProvenance.sourceExcerpt,calendarEvent.conversationProvenance.sourceExcerpt,'Calendar personal text is exported intact');
assert.equal(service.prepareImport(exported).preview.restorable,true); assert.deepEqual(service.getExportPreview().resourceSummaries.map(r=>r.count),[2,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1]);
for(const definition of BACKUP_RESOURCE_REGISTRY) assert.equal(definition.validate(fixtures[definition.name]),true,`${definition.name} fixture`);
const requiredPath:Record<string,string[]>= {dailyLogs:['id'],calendarEvents:['records'],sleepRecords:['durationMinutes'],baseLocation:['location'],weatherForecastSnapshots:['records'],observedWeatherRecords:['records'],evidence:['title'],understandingCandidates:['explanation'],candidateResponses:['answer'],understandingObjects:['statement'],understandingHistory:['records'],formalUserModel:['userId'],legacyInsights:['message'],legacyUserModel:['userId'],legacyUserModelUpdateCandidates:['targetField'],legacyUserModelUpdateHistory:['appliedAt']};
for(const definition of BACKUP_RESOURCE_REGISTRY){const broken=structuredClone(fixtures[definition.name]) as any;let target:any=broken;if(Array.isArray(target))target=target[0];delete target[requiredPath[definition.name][0]];assert.equal(definition.validate(broken),false,`${definition.name} required field`)}
const brokenCandidateRef=structuredClone(envelope) as any;brokenCandidateRef.resources.find((r:any)=>r.name==='understandingCandidates').data[0].evidenceIds=['missing'];assert.equal(service.prepareImport(JSON.stringify(brokenCandidateRef)).preview.errors.some(e=>e.code==='BROKEN_REFERENCE'),true);
const brokenResponseRef=structuredClone(envelope) as any;brokenResponseRef.resources.find((r:any)=>r.name==='candidateResponses').data[0].candidateId='missing';assert.equal(service.prepareImport(JSON.stringify(brokenResponseRef)).preview.errors.some(e=>e.code==='BROKEN_REFERENCE'),true);
const brokenObjectRef=structuredClone(envelope) as any;brokenObjectRef.resources.find((r:any)=>r.name==='understandingObjects').data[0].evidenceIds=['missing'];assert.equal(service.prepareImport(JSON.stringify(brokenObjectRef)).preview.errors.some(e=>e.code==='BROKEN_REFERENCE'),true);
const brokenFormalRef=structuredClone(envelope) as any;brokenFormalRef.resources.find((r:any)=>r.name==='formalUserModel').data.understandingIds.longTerm=['missing'];assert.equal(service.prepareImport(JSON.stringify(brokenFormalRef)).preview.errors.some(e=>e.code==='BROKEN_REFERENCE'),true);
const badConfidence=structuredClone(envelope);(badConfidence.resources.find(r=>r.name==='evidence')!.data as any[])[0].confidence=2;assert.equal(service.prepareImport(JSON.stringify(badConfidence)).preview.restorable,false);
const badProvenance=structuredClone(envelope) as any;badProvenance.resources.find((r:any)=>r.name==='dailyLogs').data.find((log:any)=>log.captureProvenance).captureProvenance.extraction.method='LLM';assert.equal(service.prepareImport(JSON.stringify(badProvenance)).preview.restorable,false,'不正provenanceを拒否する');
const badHistory=structuredClone(envelope) as any;delete badHistory.resources.find((r:any)=>r.name==='understandingHistory').data.records[0].candidateTitle;let badHistoryPreview=service.prepareImport(JSON.stringify(badHistory)).preview;assert.equal(badHistoryPreview.restorable,false);assert.equal(badHistoryPreview.errors.some(e=>e.code==='INVALID_RESOURCE_DATA'&&e.resourceName==='understandingHistory'),true,'不正history eventを拒否する');
const duplicateHistory=structuredClone(envelope) as any;const historyData=duplicateHistory.resources.find((r:any)=>r.name==='understandingHistory').data;historyData.records.push(structuredClone(historyData.records[0]));badHistoryPreview=service.prepareImport(JSON.stringify(duplicateHistory)).preview;assert.equal(badHistoryPreview.restorable,false,'重複history event IDを拒否する');
const invalidCalendar=structuredClone(envelope) as any;invalidCalendar.resources.find((r:any)=>r.name==='calendarEvents').data.records[0].title='';assert.equal(service.prepareImport(JSON.stringify(invalidCalendar)).preview.restorable,false,'one invalid Calendar record rejects the whole restore');
const duplicateCalendar=structuredClone(envelope) as any;const calendarRecords=duplicateCalendar.resources.find((r:any)=>r.name==='calendarEvents').data.records;calendarRecords.push(structuredClone(calendarRecords[0]));assert.equal(service.prepareImport(JSON.stringify(duplicateCalendar)).preview.restorable,false,'duplicate Calendar IDs are rejected');
const emptyStorage=new MemoryStorage();const emptyService=new BackupApplicationService(emptyStorage,BACKUP_RESOURCE_REGISTRY,()=>t);const empty=emptyService.export();assert.equal(JSON.parse(empty).resources.length,16);assert.equal(emptyService.prepareImport(empty).preview.warnings.length,16);
const unknown=structuredClone(envelope) as any;unknown.resources.push({name:'futureData',schemaVersion:1,data:[{id:'x'}]});let preview=service.prepareImport(JSON.stringify(unknown)).preview;assert.equal(preview.restorable,false);assert.deepEqual(preview.unknownResources.map(r=>[r.name,r.count,r.occurrences]),[['futureData',1,1]]);
const missing=structuredClone(envelope) as any;missing.resources.pop();preview=service.prepareImport(JSON.stringify(missing)).preview;assert.deepEqual(preview.missingResources,['legacyUserModelUpdateHistory']);
const duplicate=structuredClone(envelope) as any;duplicate.resources.push(duplicate.resources[0]);preview=service.prepareImport(JSON.stringify(duplicate)).preview;assert.deepEqual(preview.duplicateResources,['dailyLogs']);
const reverse=populatedStorage();reverse.setItem('compass_daily_logs',JSON.stringify([...(fixtures.dailyLogs as any[])].reverse()));assert.equal(new BackupApplicationService(reverse,BACKUP_RESOURCE_REGISTRY,()=>t).export(),exported,'array output order is deterministic');
const reverseHistory=populatedStorage();const reversedHistory=structuredClone(fixtures.understandingHistory) as any;reversedHistory.records.reverse();reverseHistory.setItem('compass_understanding_history_v1',JSON.stringify(reversedHistory));assert.equal(new BackupApplicationService(reverseHistory,BACKUP_RESOURCE_REGISTRY,()=>t).export(),exported,'history output order is deterministic');
const replacement=structuredClone(envelope) as any;(replacement.resources.find((r:any)=>r.name==='dailyLogs').data as any[])[0].note='restored';const prepared=service.prepareImport(JSON.stringify(replacement));const immutable=JSON.stringify(replacement);service.restore(prepared);assert.equal(JSON.parse(storage.getItem('compass_daily_logs')!)[0].note,'restored');assert.equal(JSON.stringify(replacement),immutable);assert.equal(storage.getItem('not-managed'),'keep');assert.equal(reconciles,1);
const restoredCalendar=JSON.parse(storage.getItem('compass_calendar_event_records_v1')!).records[0];assert.equal(restoredCalendar.title,calendarEvent.title);assert.equal(restoredCalendar.note,calendarEvent.note);assert.equal(restoredCalendar.conversationProvenance.sourceExcerpt,calendarEvent.conversationProvenance.sourceExcerpt,'Calendar personal text is restored intact');
const restoredHistory=JSON.parse(storage.getItem('compass_understanding_history_v1')!);assert.deepEqual(restoredHistory.records.map((event:any)=>event.id),['history-2','history-1'],'restore後も新しい順を維持する');assert.equal(restoredHistory.records[0].candidateStatement,'statement','snapshotを維持する');
assert.equal(JSON.parse(storage.getItem('compass_daily_logs')!).find((log:any)=>log.captureProvenance).captureProvenance.sourceExcerpt,'excerpt','provenance付きDailyLogをrestoreする');
const oldBackup=structuredClone(envelope) as any;oldBackup.resources=oldBackup.resources.filter((resource:any)=>resource.name!=='understandingHistory');const oldPreview=service.prepareImport(JSON.stringify(oldBackup));assert.equal(oldPreview.preview.restorable,true,'historyのない旧backupを復元可能にする');assert.equal(oldPreview.preview.warnings.some(w=>w.code==='LEGACY_BACKUP_WITHOUT_HISTORY'),true);const oldTarget=populatedStorage();new BackupApplicationService(oldTarget,BACKUP_RESOURCE_REGISTRY,()=>t).restore(new BackupApplicationService(oldTarget,BACKUP_RESOURCE_REGISTRY,()=>t).prepareImport(JSON.stringify(oldBackup)));assert.deepEqual(JSON.parse(oldTarget.getItem('compass_understanding_history_v1')!),{schemaVersion:1,records:[]},'旧backupから履歴を推測しない');
const preCalendarBackup=structuredClone(envelope) as any;preCalendarBackup.resources=preCalendarBackup.resources.filter((resource:any)=>resource.name!=='calendarEvents');const preCalendarPrepared=service.prepareImport(JSON.stringify(preCalendarBackup));assert.equal(preCalendarPrepared.preview.restorable,true,'Calendar resourceだけがない旧backupを復元できる');const preCalendarTarget=populatedStorage();const preCalendarService=new BackupApplicationService(preCalendarTarget,BACKUP_RESOURCE_REGISTRY,()=>t);preCalendarService.restore(preCalendarService.prepareImport(JSON.stringify(preCalendarBackup)));assert.deepEqual(JSON.parse(preCalendarTarget.getItem('compass_calendar_event_records_v1')!),{schemaVersion:1,records:[]});
const tamperedPrepared=service.prepareImport(exported) as any;tamperedPrepared.envelope.resources.find((r:any)=>r.name==='calendarEvents').data.records[0].title='';const tamperBefore=new Map(storage.values);assert.throws(()=>service.restore(tamperedPrepared),/再検証/);assert.deepEqual(storage.values,tamperBefore,'restore uses the same validation and writes nothing after preparation is tampered');
const before=new Map(storage.values);storage.failOnceOnKey='compass_analysis_evidence';assert.throws(()=>service.restore(prepared));assert.deepEqual(storage.values,before,'write rollback');
const reconcileFailureStorage=populatedStorage();const failing=new BackupApplicationService(reconcileFailureStorage,BACKUP_RESOURCE_REGISTRY,()=>t,()=>{throw Error('reconcile')});const reconcileBefore=new Map(reconcileFailureStorage.values);assert.throws(()=>failing.restore(failing.prepareImport(exported)));assert.deepEqual(reconcileFailureStorage.values,reconcileBefore,'reconcile rollback');
const app=readFileSync(new URL('../src/app/App.tsx',import.meta.url),'utf8');assert.match(app,/generateAndSaveFromEvidence/);assert.match(app,/reconcileAll/);const restoreRefresh=app.match(/const refreshAfterRestore = \(\) => \{([\s\S]*?)\n[ ]{2}\};/)?.[1] ?? '';assert.doesNotMatch(restoreRefresh,/setConversationSession/, 'restore preserves the open in-memory conversation session');const composition=readFileSync(new URL('../src/features/backup/services/index.ts',import.meta.url),'utf8');assert.doesNotMatch(composition,/analysisApplicationService|generateAndSaveFromEvidence|reconcileAll/);
const backupPanel=readFileSync(new URL('../src/features/backup/components/BackupPanel.tsx',import.meta.url),'utf8');assert.match(backupPanel,/予定のタイトル・メモ/);assert.match(backupPanel,/発言抜粋/,'Calendar personal-data boundary is disclosed');
const ui=readFileSync(new URL('../src/features/backup/components/BackupPanel.tsx',import.meta.url),'utf8');assert.doesNotMatch(ui,/localStorage|Repository|location\.reload/);

// Known stored legacy shapes are decoded and normalized for the backup without mutating storage.
const legacyStorage=populatedStorage();
const currentInsight=(fixtures.legacyInsights as any[])[0];
const withoutDedupe={...currentInsight,id:'legacy-no-dedupe'};delete withoutDedupe.dedupeKey;
const oldEvidence={...currentInsight,id:'legacy-old-evidence',evidence:['old summary']};delete oldEvidence.evidenceSummaries;
const beforeEvidenceRefs={...currentInsight,id:'legacy-no-refs'};delete beforeEvidenceRefs.evidenceRefs;
legacyStorage.setItem('compass_insights',JSON.stringify([withoutDedupe,oldEvidence,beforeEvidenceRefs]));
const dismissed={...(fixtures.legacyUserModelUpdateCandidates as any[])[0],status:'DISMISSED'};
legacyStorage.setItem('compass_user_model_update_candidates',JSON.stringify([dismissed]));
const historicalDailyLog={...(fixtures.dailyLogs as any[])[0],sleepHours:7.5};
legacyStorage.setItem('compass_daily_logs',JSON.stringify([historicalDailyLog]));
const rawBefore=new Map(legacyStorage.values);
const legacyService=new BackupApplicationService(legacyStorage,BACKUP_RESOURCE_REGISTRY,()=>t);
const legacyExport=legacyService.export();
assert.deepEqual(legacyStorage.values,rawBefore,'export must not mutate stored legacy data');
const normalizedEnvelope=JSON.parse(legacyExport) as BackupEnvelope;
const normalizedInsights=normalizedEnvelope.resources.find((item)=>item.name==='legacyInsights')!.data as any[];
assert.equal(normalizedInsights.every((item)=>typeof item.dedupeKey==='string'),true);
assert.deepEqual(normalizedInsights.find((item)=>item.id==='legacy-old-evidence').evidenceSummaries,['old summary']);
assert.deepEqual(normalizedInsights.find((item)=>item.id==='legacy-no-refs').evidenceRefs,[],'missing references are not guessed');
assert.equal((normalizedEnvelope.resources.find((item)=>item.name==='legacyUserModelUpdateCandidates')!.data as any[])[0].status,'REJECTED');
const restoredLegacy=new MemoryStorage();
new BackupApplicationService(restoredLegacy,BACKUP_RESOURCE_REGISTRY,()=>t).restore(new BackupApplicationService(restoredLegacy,BACKUP_RESOURCE_REGISTRY,()=>t).prepareImport(legacyExport));
Object.defineProperty(globalThis,'localStorage',{value:restoredLegacy,configurable:true});
assert.equal(new LocalStorageInsightRepository().getAll().length,3,'existing Insight repository reads restored normalized legacy data');
assert.equal(new LocalStorageLogRepository().getAll()[0].sleepHours,7.5,'historical DailyLog meaning is preserved');
assert.equal(new LocalStorageUserModelUpdateCandidateRepository().getAll()[0].status,'REJECTED','existing candidate repository reads normalized status');
const resemblesLegacy={...currentInsight,id:'invalid-lookalike',evidence:['summary']};delete resemblesLegacy.evidenceSummaries;delete resemblesLegacy.evidenceRefs;delete resemblesLegacy.createdAt;
legacyStorage.setItem('compass_insights',JSON.stringify([resemblesLegacy]));
assert.throws(()=>legacyService.export(),/既知の保存形式/,'unsafe lookalike must be rejected');
console.log('backup tests passed');
