import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { answerDailyLogCaptureStep, cancelDailyLogCaptureFlow, completeDailyLogCaptureFlow, moveBackDailyLogCaptureFlow, normalizeEvents, startDailyLogCaptureFlow } from '../src/features/conversation/session/dailyLogCaptureFlow.ts';
import { answerActiveDailyLogCaptureFlow, completeActiveDailyLogCaptureFlow, createConversationSession, transitionConversationSession } from '../src/features/conversation/session/conversationSession.ts';
const initial = createConversationSession();
assert.equal(transitionConversationSession(initial, { type: 'SUBMIT_TEXT', text: '今日は少し疲れています' }).dailyLogCaptureFlow, null);
assert.equal(transitionConversationSession(initial, { type: 'SUBMIT_TEXT', text: '疲れているので相談したい' }).dailyLogCaptureFlow, null);
let session = transitionConversationSession(initial, { type: 'SUBMIT_TEXT', text: '今日の体調を記録したい' });
assert.equal(session.dailyLogCaptureFlow?.step, 'DATE'); assert.equal(session.activeCaptureCandidate, null);
assert.equal(session.dailyLogCaptureFlow?.sourceMessageId, 'message-1'); assert.equal(session.dailyLogCaptureFlow?.sourceExcerpt, '今日の体調を記録したい');
const existingFlow = session.dailyLogCaptureFlow;
session = transitionConversationSession(session, { type: 'SUBMIT_TEXT', text: '日記を記録したい' });
assert.equal(session.dailyLogCaptureFlow, existingFlow);
assert.deepEqual(answerDailyLogCaptureStep(null, { step: 'DATE', value: '2026-08-02' }), { ok: false, reason: 'NO_ACTIVE_FLOW' });
assert.deepEqual(answerDailyLogCaptureStep(existingFlow, { step: 'MOOD', value: 3 }), { ok: false, reason: 'STEP_MISMATCH' });
assert.deepEqual(answerDailyLogCaptureStep(existingFlow, { step: 'DATE', value: '2026-02-30' }), { ok: false, reason: 'INVALID_DATE' });
let result = answerActiveDailyLogCaptureFlow(session, { step: 'DATE', value: '2026-08-02' }); session = result.session; assert.equal(session.dailyLogCaptureFlow?.step, 'MOOD');
assert.equal(answerActiveDailyLogCaptureFlow(session, { step: 'MOOD', value: 0 }).error, 'INVALID_SCALE');
result = answerActiveDailyLogCaptureFlow(session, { step: 'MOOD', value: 4 }); session = result.session; assert.equal(session.dailyLogCaptureFlow?.step, 'FATIGUE');
result = answerActiveDailyLogCaptureFlow(session, { step: 'FATIGUE', value: 5 }); session = result.session; assert.equal(session.dailyLogCaptureFlow?.step, 'NOTE');
const backed = moveBackDailyLogCaptureFlow(session.dailyLogCaptureFlow); assert.equal(backed.ok && backed.flow?.step, 'FATIGUE');
result = answerActiveDailyLogCaptureFlow(session, { step: 'NOTE', value: '' }); session = result.session; assert.equal(session.dailyLogCaptureFlow?.step, 'EVENTS');
assert.equal(completeActiveDailyLogCaptureFlow(session, '2026-08-02T10:00:00.000Z').error, 'FLOW_INCOMPLETE');
result = answerActiveDailyLogCaptureFlow(session, { step: 'EVENTS', value: '  散歩  \n\n  読書\n ' }); session = result.session;
session = completeActiveDailyLogCaptureFlow(session, '2026-08-02T10:00:00.000Z').session;
assert.equal(session.dailyLogCaptureFlow, null); assert.equal(session.activeCaptureCandidate?.status, 'PROPOSED');
assert.equal(session.activeCaptureCandidate?.extraction.method, 'USER_STRUCTURED_INPUT');
assert.deepEqual(session.activeCaptureCandidate?.proposedPayload, { date: '2026-08-02', mood: { value: 4, origin: 'USER_EXPLICIT' }, fatigue: { value: 5, origin: 'USER_EXPLICIT' }, note: '', events: ['散歩', '読書'] });
assert.equal(session.activeCaptureCandidate?.sourceExcerpt, '今日の体調を記録したい');
assert.equal(transitionConversationSession(session, { type: 'SUBMIT_TEXT', text: '日記を記録したい' }).dailyLogCaptureFlow, null);
assert.equal(transitionConversationSession(session, { type: 'RESET' }).dailyLogCaptureFlow, null);
const start = startDailyLogCaptureFlow(null, { sourceMessageId: 'm1', sourceExcerpt: '記録する', startedAt: '2026-08-02T00:00:00Z', deduplicationKey: 'session-1' });
assert.equal(start.ok, true); if (start.ok) { assert.equal(startDailyLogCaptureFlow(start.flow, { sourceMessageId: 'm2', sourceExcerpt: '別', startedAt: '2026-08-02T00:00:00Z', deduplicationKey: 'session-2' }).ok, false); assert.equal(cancelDailyLogCaptureFlow(start.flow).ok, true); }
assert.deepEqual(cancelDailyLogCaptureFlow(null), { ok: false, reason: 'NO_ACTIVE_FLOW' });
assert.deepEqual(completeDailyLogCaptureFlow(null, { id: 'x', createdAt: '2026-08-02T00:00:00Z' }), { ok: false, reason: 'NO_ACTIVE_FLOW' });
assert.deepEqual(normalizeEvents(''), [], 'events supports none');
const flowUi = readFileSync(new URL('../src/features/conversation/components/DailyLogCaptureFlowCard.tsx', import.meta.url), 'utf8');
for (const step of ["flow.step === 'DATE'", "flow.step === 'MOOD'", "flow.step === 'FATIGUE'", "flow.step === 'NOTE'", "flow.step === 'EVENTS'"]) assert.match(flowUi, new RegExp(step.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')));
assert.match(flowUi, /手順 \{STEP_NUMBER\[flow\.step\]\} \/ 5/);
assert.match(flowUi, /高いほど疲れている/);
const captureSources = [flowUi, readFileSync(new URL('../src/features/conversation/session/dailyLogCaptureFlow.ts', import.meta.url), 'utf8')].join('\n');
assert.doesNotMatch(captureSources, /localStorage|Repository|DailyLogApplicationService|backup/);
console.log('daily log capture flow tests passed');
