import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { createCaptureCandidate } from '../src/features/conversation/session/captureCandidateLifecycle.ts';
import { applyActiveCaptureCandidateEdit, beginActiveCaptureCandidateEdit, createConversationSession, markActiveCaptureCandidateReady, presentCaptureCandidate, rejectActiveCaptureCandidate, requestActiveCaptureCandidateCommit, transitionConversationSession } from '../src/features/conversation/session/conversationSession.ts';
import { presentCaptureCandidateReview } from '../src/features/conversation/components/captureCandidatePresentation.ts';
import type { DateString } from '../src/features/daily-log/types/log.ts';
const date='2026-08-02' as DateString, now='2026-08-02T10:00:00Z';
const make=(id:string,sensitivity:'NON_SENSITIVE'|'SENSITIVE_REQUIRES_SEPARATE_CONSENT'='NON_SENSITIVE')=>{const r=createCaptureCandidate({id,destinationType:'DAILY_LOG',purpose:'今日を振り返るため',targetDate:date,proposedPayload:{date,mood:{value:null,origin:'UNSPECIFIED'},fatigue:{value:null,origin:'UNSPECIFIED'},note:'長いメモ'.repeat(30),events:['散歩']},sourceMessageId:'message-1',sourceExcerpt:'今日は散歩した',conversationOccurredAt:now,extraction:{method:'USER_STRUCTURED_INPUT',version:'v1'},sensitivity,deduplicationKey:id,createdAt:now});if(!r.ok)throw Error('fixture');return r.candidate};
let session=createConversationSession(); assert.equal(session.activeCaptureCandidate,null);
session=presentCaptureCandidate(session,make('one')).session; assert.equal(session.activeCaptureCandidate?.id,'one');
const duplicate=presentCaptureCandidate(session,make('two')); assert.equal(duplicate.error,'ACTIVE_CANDIDATE_EXISTS'); assert.equal(duplicate.session.activeCaptureCandidate?.id,'one');
session=beginActiveCaptureCandidateEdit(session,now).session; assert.equal(session.activeCaptureCandidate?.status,'EDITING');
const payload={...session.activeCaptureCandidate!.proposedPayload,mood:{value:4 as const,origin:'USER_EXPLICIT' as const},fatigue:{value:3 as const,origin:'USER_EXPLICIT' as const}};
session=applyActiveCaptureCandidateEdit(session,payload,now).session; assert.equal(session.activeCaptureCandidate?.status,'EDITING');
session=markActiveCaptureCandidateReady(session,now).session; assert.equal(session.activeCaptureCandidate?.status,'READY'); assert.equal(presentCaptureCandidateReview(session.activeCaptureCandidate!).statusLabel,'確認済み・未保存');
const requested=requestActiveCaptureCandidateCommit(session,now); assert.ok(requested.commitRequest); assert.equal(requested.session.activeCaptureCandidate?.status,'COMMITTING'); assert.equal(requestActiveCaptureCandidateCommit(requested.session,now).commitRequest,undefined);
assert.equal(requestActiveCaptureCandidateCommit(createConversationSession(),now).commitRequest,undefined); assert.equal(requestActiveCaptureCandidateCommit(presentCaptureCandidate(createConversationSession(),make('proposed')).session,now).commitRequest,undefined);
assert.equal(rejectActiveCaptureCandidate(presentCaptureCandidate(createConversationSession(),make('reject')).session,now).session.activeCaptureCandidate,null);
assert.equal(transitionConversationSession(session,{type:'RESET'}).activeCaptureCandidate,null);
assert.equal(presentCaptureCandidateReview(make('sensitive','SENSITIVE_REQUIRES_SEPARATE_CONSENT')).saveAllowed,false); assert.equal(presentCaptureCandidateReview(make('plain')).fatigueHelp,'疲労は高いほど疲れている');
const source=await readFile(new URL('../src/features/conversation/session/conversationSession.ts',import.meta.url),'utf8'); assert.doesNotMatch(source,/localStorage|Repository|backup|DailyLogApplicationService/);
console.log('capture candidate review tests passed');
