import assert from 'node:assert/strict';
import { claimConversationAction, createConversationSession, createDailyLogNavigationTarget, dismissCommittedReceiptForRecordChange, presentCaptureCandidate, rejectActiveCaptureCandidate, cancelActiveCaptureCandidate, transitionConversationSession } from '../src/features/conversation/session/conversationSession.ts';
import { createCaptureCandidate } from '../src/features/conversation/session/captureCandidateLifecycle.ts';
import type { DateString, EntryId } from '../src/features/daily-log/types/log.ts';

const initial = createConversationSession();
assert.equal(initial.messages.length, 1);
assert.equal(initial.messages[0].role, 'assistant');
assert.equal(transitionConversationSession(initial, { type: 'SUBMIT_TEXT', text: '   ', occurredAt: '2026-08-02T09:00:00.000Z' }), initial);
const transitioned = transitionConversationSession(initial, { type: 'SUBMIT_TEXT', text: '  今日は少し疲れました  ', occurredAt: '2026-08-02T09:00:00.000Z' });
assert.deepEqual(transitioned.messages.map(({ role }) => role), ['assistant', 'user', 'assistant']);
assert.equal(transitioned.messages[1].text, '今日は少し疲れました');
assert.match(transitioned.messages[2].text, /案内先を選べませんでした/);
assert.equal(initial.messages.length, 1, 'transition must not mutate its input');
const repeated = transitionConversationSession(transitioned, { type: 'SUBMIT_TEXT', text: 'もう一つ', occurredAt: '2026-08-02T09:01:00.000Z' });
assert.equal(repeated.messages.length, 5);
assert.equal(new Set(repeated.messages.map(({ id }) => id)).size, 5);
const reset = transitionConversationSession(repeated, { type: 'RESET' });
assert.deepEqual(reset, createConversationSession());
assert.notEqual(reset, initial, 'reset creates a fresh in-memory session');
const extractedCalendar = transitionConversationSession(initial, { type: 'SUBMIT_TEXT', text: '明日の14時から15時まで歯医者の予定を入れたい', occurredAt: '2026-08-03T15:30:00.000Z' });
const resolvedTomorrow = new Intl.DateTimeFormat('en-CA', { timeZone: Intl.DateTimeFormat().resolvedOptions().timeZone || 'UTC', year:'numeric', month:'2-digit', day:'2-digit' }).format(new Date('2026-08-04T15:30:00.000Z'));
assert.equal(extractedCalendar.calendarCapture.flow, null, 'known fields are not asked again');
assert.deepEqual(extractedCalendar.calendarCapture.candidate?.draft, { title:'歯医者',note:'',timeKind:'TIMED',startDate:'',endDate:'',startsAt:`${resolvedTomorrow}T14:00`,endsAt:`${resolvedTomorrow}T15:00`,timeZone:Intl.DateTimeFormat().resolvedOptions().timeZone || 'UTC',dateHint:resolvedTomorrow });
assert.equal(extractedCalendar.calendarCapture.candidate?.status, 'PROPOSED', 'extraction remains an unsaved Candidate');
const missingEnd = transitionConversationSession(initial, { type: 'SUBMIT_TEXT', text: '来週月曜日の10時に病院へ行く予定を保存したい', occurredAt: '2026-08-03T00:00:00.000Z' });
assert.equal(missingEnd.calendarCapture.flow?.step, 'ENDS_AT', 'only the missing end time is requested');
const dateOnly = transitionConversationSession(initial, { type: 'SUBMIT_TEXT', text: '8月10日に面接の予定を追加したい', occurredAt: '2026-08-03T00:00:00.000Z' });
assert.equal(dateOnly.calendarCapture.flow?.step, 'TIME_KIND');
assert.equal(dateOnly.calendarCapture.flow?.draft.title, '面接');
assert.equal(dateOnly.calendarCapture.flow?.draft.dateHint, '2026-08-10');
assert.equal(dateOnly.calendarCapture.flow?.draft.timeKind, '', 'date-only input must not silently become all-day');
const blockedCalendar = transitionConversationSession(extractedCalendar, { type: 'SUBMIT_TEXT', text: '明日の16時から17時まで会議の予定を入れたい', occurredAt: '2026-08-03T15:31:00.000Z' });
assert.equal(blockedCalendar.calendarCapture, extractedCalendar.calendarCapture, 'an active Candidate is not replaced');
assert.match(blockedCalendar.messages.at(-1)?.text ?? '', /開始できませんでした/);
assert.doesNotMatch(blockedCalendar.messages.at(-1)?.text ?? '', /開始します/);
const invalidCalendarTime = transitionConversationSession(initial, { type: 'SUBMIT_TEXT', text: '明日の14時から15時まで歯医者の予定を入れたい', occurredAt: 'invalid' });
assert.equal(invalidCalendarTime.calendarCapture.flow, null);
assert.equal(invalidCalendarTime.calendarCapture.candidate, null);
assert.match(invalidCalendarTime.messages.at(-1)?.text ?? '', /開始できませんでした/);
const actionable = transitionConversationSession(initial, { type: 'SUBMIT_TEXT', text: '睡眠を記録したい', occurredAt: '2026-08-02T09:00:00.000Z' });
const actionMessage = actionable.messages.at(-1)!;
assert.equal(actionMessage.action?.intent, 'RECORD_SLEEP');
const firstClaim = claimConversationAction(actionable, actionMessage.id);
assert.equal(firstClaim.intent, 'RECORD_SLEEP');
assert.equal(firstClaim.session.messages.at(-1)?.action?.executed, true);
const secondClaim = claimConversationAction(firstClaim.session, actionMessage.id);
assert.equal(secondClaim.intent, undefined, 'an action can only be claimed once');
assert.equal(secondClaim.session, firstClaim.session);

const candidateResult = createCaptureCandidate({ id:'capture-1', destinationType:'DAILY_LOG', purpose:'記録', targetDate:'2026-08-02' as DateString,
  proposedPayload:{date:'2026-08-02' as DateString,mood:{value:3,origin:'USER_EXPLICIT'},fatigue:{value:2,origin:'USER_EXPLICIT'},note:'secret payload',events:[]},
  sourceMessageId:'message-secret',sourceExcerpt:'secret excerpt',conversationOccurredAt:'2026-08-02T09:00:00Z',extraction:{method:'USER_STRUCTURED_INPUT',version:'v1'},sensitivity:'NON_SENSITIVE',deduplicationKey:'same-key',createdAt:'2026-08-02T09:00:00Z' });
if (!candidateResult.ok) throw new Error('candidate fixture');
const presented = presentCaptureCandidate(createConversationSession(), candidateResult.candidate);
const rejectedSession = rejectActiveCaptureCandidate(presented.session, '2026-08-02T09:01:00Z').session;
assert.deepEqual(rejectedSession.rejectedDeduplicationKeys, ['same-key'], 'reject records only the key');
assert.doesNotMatch(JSON.stringify(rejectedSession.rejectedDeduplicationKeys), /secret|message-/);
assert.equal(presentCaptureCandidate(rejectedSession, candidateResult.candidate).error, 'CAPTURE_SUPPRESSED', 'same key is suppressed');
const different = { ...candidateResult.candidate, id:'capture-2' as typeof candidateResult.candidate.id, deduplicationKey:'different-key' };
assert.equal(presentCaptureCandidate(rejectedSession, different).error, undefined, 'different key remains available, including the same date');
const duplicateState = { ...rejectedSession, activeCaptureCandidate: different };
assert.deepEqual(rejectActiveCaptureCandidate(duplicateState, '2026-08-02T09:02:00Z').session.rejectedDeduplicationKeys, ['same-key','different-key']);
const rePresentedDifferent = presentCaptureCandidate(rejectedSession, different).session;
assert.deepEqual(cancelActiveCaptureCandidate(rePresentedDifferent, '2026-08-02T09:03:00Z').session.rejectedDeduplicationKeys, ['same-key'], 'cancel does not suppress');
assert.deepEqual(transitionConversationSession(rejectedSession,{type:'RESET'}).rejectedDeduplicationKeys, [], 'reset clears suppression');

const committed = { ...candidateResult.candidate, status:'COMMITTED' as const, commitResultReference:{destinationType:'DAILY_LOG' as const,recordId:'log-1',committedAt:'2026-08-02T09:01:00Z'} };
for (const action of ['VIEW','EDIT','DELETE'] as const) assert.deepEqual(createDailyLogNavigationTarget(committed, action), {recordId:'log-1',action});
assert.equal(createDailyLogNavigationTarget(candidateResult.candidate,'VIEW'), null, 'non-COMMITTED candidate cannot navigate');
const receiptSession = { ...createConversationSession(), activeCaptureCandidate: committed };
assert.equal(dismissCommittedReceiptForRecordChange(receiptSession,{recordId:'other' as EntryId,kind:'UPDATED'}), receiptSession, 'other record retains receipt');
const dismissed = dismissCommittedReceiptForRecordChange(receiptSession,{recordId:'log-1' as EntryId,kind:'DELETED'});
assert.equal(dismissed.activeCaptureCandidate, null);
assert.equal(committed.status, 'COMMITTED', 'receipt dismissal does not mutate terminal status');
console.log('conversation-session tests passed');
