import assert from 'node:assert/strict';
import { createCaptureCandidate, beginCaptureCandidateEdit, applyCaptureCandidateEdit, markCaptureCandidateReady } from '../src/features/conversation/session/captureCandidateLifecycle.ts';
import { applyCaptureCommitOutcome, createConversationSession, requestActiveCaptureCandidateCommit, retryActiveCaptureCandidate, transitionConversationSession } from '../src/features/conversation/session/conversationSession.ts';
import { executeCaptureCommit } from '../src/features/conversation/application/captureCommitExecutor.ts';
import type { CaptureCommitOutcome } from '../src/features/conversation/types/captureCandidate.ts';
import type { DateString } from '../src/features/daily-log/types/log.ts';
const date='2026-08-01' as DateString,t1='2026-08-02T10:00:00.000Z',t2='2026-08-02T10:01:00.000Z',t3='2026-08-02T10:02:00.000Z';
function ready(){const made=createCaptureCandidate({id:'c1',destinationType:'DAILY_LOG',purpose:'振り返り',proposedPayload:{date,mood:{value:4,origin:'USER_EXPLICIT'},fatigue:{value:2,origin:'USER_EXPLICIT'},note:'note',events:['event']},targetDate:date,sourceMessageId:'m1',sourceExcerpt:'excerpt',conversationOccurredAt:t1,extraction:{method:'USER_STRUCTURED_INPUT',version:'1'},sensitivity:'NON_SENSITIVE',deduplicationKey:'dedupe',createdAt:t1});if(!made.ok)throw Error();const editing=beginCaptureCandidateEdit(made.candidate,t1);if(!editing.ok)throw Error();const applied=applyCaptureCandidateEdit(editing.candidate,editing.candidate.proposedPayload,t1);if(!applied.ok)throw Error();const r=markCaptureCandidateReady(applied.candidate,t1);if(!r.ok)throw Error();return {...createConversationSession(),activeCaptureCandidate:r.candidate}}
const begun=requestActiveCaptureCandidateCommit(ready(),t2);assert.equal(begun.session.activeCaptureCandidate?.status,'COMMITTING');const request=begun.commitRequest!;
const success:CaptureCommitOutcome={ok:true,reference:{destinationType:'DAILY_LOG',recordId:'record-1',committedAt:t2}};
let result=applyCaptureCommitOutcome(begun.session,request,success,t3);assert.equal(result.session.activeCaptureCandidate?.status,'COMMITTED');assert.equal(result.session.activeCaptureCandidate?.commitResultReference?.recordId,'record-1');assert.equal(result.session.activeCaptureCandidate?.commitResultReference?.committedAt,t2);
assert.ok(applyCaptureCommitOutcome(result.session,request,success,t3).error,'COMMITTED rejects duplicate outcome');
const wrong={...request,candidateId:'other' as typeof request.candidateId};assert.equal(applyCaptureCommitOutcome(begun.session,wrong,success,t3).error,'CANDIDATE_ID_MISMATCH');
assert.equal(applyCaptureCommitOutcome(begun.session,{...request,consentedAt:t1},success,t3).error,'STALE_COMMIT_REQUEST');
const failure:CaptureCommitOutcome={ok:false,failure:{code:'SAVE_FAILED',message:'safe',failedAt:t3,retryable:true}};result=applyCaptureCommitOutcome(begun.session,request,failure,t3);assert.equal(result.session.activeCaptureCandidate?.status,'FAILED');assert.deepEqual(result.session.activeCaptureCandidate?.proposedPayload,begun.session.activeCaptureCandidate?.proposedPayload);assert.equal(result.session.activeCaptureCandidate?.sourceExcerpt,'excerpt');assert.equal(result.session.activeCaptureCandidate?.purpose,'振り返り');
const retried=retryActiveCaptureCandidate(result.session,t3);assert.equal(retried.session.activeCaptureCandidate?.status,'READY');const second=requestActiveCaptureCandidateCommit(retried.session,'2026-08-02T10:03:00.000Z');assert.equal(second.session.activeCaptureCandidate?.status,'COMMITTING');assert.equal(applyCaptureCommitOutcome(second.session,second.commitRequest!,success,t3).session.activeCaptureCandidate?.status,'COMMITTED');
const noRetry=applyCaptureCommitOutcome(begun.session,request,{ok:false,failure:{...failure.failure,retryable:false}},t3);assert.equal(retryActiveCaptureCandidate(noRetry.session,t3).error,'NOT_RETRYABLE');
for(const callback of [()=>{throw Error('internal')},()=>Promise.reject(Error('internal')),()=>Promise.resolve(null as never)]){let current=begun.session;current=await executeCaptureCommit(request,callback,()=>current,()=>t3);assert.equal(current.activeCaptureCandidate?.status,'FAILED');assert.equal(current.activeCaptureCandidate?.failure?.code,'CAPTURE_COMMIT_UNAVAILABLE');assert.equal(current.activeCaptureCandidate?.failure?.retryable,true);assert.doesNotMatch(current.activeCaptureCandidate?.failure?.message??'',/internal/)}
let resolve!: (value:CaptureCommitOutcome)=>void;const deferred=new Promise<CaptureCommitOutcome>(r=>resolve=r);let current=begun.session;const pending=executeCaptureCommit(request,()=>deferred,()=>current,()=>t3);current=transitionConversationSession(current,{type:'RESET'});resolve(success);const afterReset=await pending;assert.equal(afterReset,current);assert.equal(afterReset.activeCaptureCandidate,null,'stale outcome never resurrects reset candidate');
let resolveOld!: (value:CaptureCommitOutcome)=>void;const oldDeferred=new Promise<CaptureCommitOutcome>(r=>resolveOld=r);current=begun.session;const oldPending=executeCaptureCommit(request,()=>oldDeferred,()=>current,()=>t3);const failed=applyCaptureCommitOutcome(current,request,failure,t3).session;const nextReady=retryActiveCaptureCandidate(failed,t3).session;current=requestActiveCaptureCandidateCommit(nextReady,'2026-08-02T10:04:00.000Z').session;resolveOld(success);assert.equal(await oldPending,current,'an old attempt cannot overwrite a newer COMMITTING attempt');
console.log('capture commit executor tests passed');
